### PR TITLE
chore: makefile and github workflow

### PR DESCRIPTION
**Pull request by rnithinpaladin**
1. Created Root makefile 
2. Github action to build executable and push to S3 buckets 

## Release Notes

- **New Features**
	- Updated workflow for building executables and deploying Lambda layers, enhancing clarity and functionality.
	- Introduced a structured Makefile for packaging multiple services, ensuring organized output and error handling.
	- Added new jobs to the build process, including checks for release branches and manual approval steps for deployments.
	- Implemented a new Makefile for the `svc-asset-delta-engine` service, streamlining the build and packaging process.
	- Added additional Makefiles for asset management services, improving the packaging process for `svc-asset-violations`, `svc-asset-network-rules`, and `svc-asset-details`.

- **Bug Fixes**
	- Improved error handling in packaging processes to ensure successful builds and zipping of artifacts.

- **Documentation**
	- Updated `.gitignore` to exclude specific generated files related to AWS Lambda functions and layers from version control, maintaining a clean repository.

### CODE REVIEW

**Review by plyubich — APPROVED** [review]
please look at code rabbit comments, it has useful insights

**Comment by rnithinpaladin** [comment]
@coderabbitai review

**Comment by rnithinpaladin** [comment]
@coderabbitai full review

**Comment by rnithinpaladin** [comment]
@coderabbitai resolve

**Pull request closed without merging**
